### ISSUE TITLE
minimodem seams not to work at 1200bps

### ISSUE THREAD

**Issue by rjesus-eid** [kamalmostafa/minimodem#11]
I'm not being able to use minimodem for '1200/2100/1300' (baud/mark/space).
Is there an explanation for this?
I'm working on Ubuntu 14.04 with minimodem 0.21.

(I'am sorry, but I put this question on a wrong place (other issue)!)

**Comment by kamalmostafa** [comment]
Those settings seem to work okay for me, specifically:

    machineA$  date | minimodem --tx 1200 -M 2100 -S 1300
    machineB$  minimodem --rx 1200 -M 2100 -S 1300 
    ### CARRIER 1200 @ 2200.0 Hz ###
    Tue Apr 21 09:50:18 PDT 2015

    ### NOCARRIER ndata=29 confidence=1.917 ampl=0.879 bps=1201.66 (0.1% fast) ###

That said, I have recently observed an injected noise problem on some systems (which I believe to be caused by PulseAudio resampling)...  Try adding "-A" to your --tx command line (or your --rx command line, or both) to select ALSA instead, and experiment with that.

Another tip:  Check the "ampl=" values that minimodem emits -- a normal value will be 0.5 to 1.0.  If you see values like 0.000 or 0.001, its likely that minimodem is "listening" on the wrong audio channel altogether (which surprisingly sometimes works anyway -- but unreliably -- just by the signal bleeding through).  In that case, check your PulseAudio or ALSA configuration, or move your audio input plug to the correct socket.

**Comment by brannondorsey** [comment]
On Ubuntu 16.04 I've got heavy noise and interference with default settings. Each transmission sounds like %50 garbage making RX impossible. Switching over to ALSA using `-A` did the charm.
