### ISSUE TITLE
minimodem with Raspberry Pi

### ISSUE THREAD

**Issue by MoaidHathot** [kamalmostafa/minimodem#18]
First of all, minimodem is awesome!

Though, I'm failing to make the Raspberry pi the receiving end. It just doesn't receive any data (I even don't see the on-screen logs).
I'm using a Raspberry Pi 2 with a Cirrus Logic Audio Card.
Did somebody tried it out?

**Comment by medouederni** [comment]
Did you cross compile minimodem to armv7 ? I'm struggling with that. Can you please provide the needed steps to cc minimodem to armv7 ?
Thank you

**Comment by nkeck720** [comment]
Does the sound card show up properly as a recording device with pulseaudio? If not, then minimodem isn't going to see the card or any sound coming from it. Also note that on some pi 2 models that only have one 3.5mm jack, that jack is going to be A/V output only, with no input capabilities. AFAIK, the only way to get audio into these is to use a USB audio input, which I'm sure you can find for cheap on ebay and the like. I have a RPi model 2B+, but since I don't have an input on it, I can't test anything for you.

Hope this helps.

**Comment by yodakohl** [comment]
Yes I tried it. See my video [https://www.youtube.com/watch?v=DfSHclXjobY]

**Comment by DREAMEnterprise** [comment]
You don't have to use Pulse Audio.  You can use ALSA if you use the -Ax tag where x is the card designator in 'aplay-l'.
