### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Zibri** [kamalmostafa/minimodem#30]
Why don't you implement also all error corrections and data compressions available at the time so to fully emulate a mode from 300 bps to 56K with MNP LAPB etc etc

**Comment by nkeck720** [comment]
Keep in mind that minimodem only supports FSK or Frequency shift keyed protocols, so that rules out anything above 1200 bps, as these were PSK or phase shift keying.

I'm not a developer for this project, but if you wanted 56k stuff I'm fairly certain @kamalmostafa would have to write the PSK modem from scratch. Besides, minimodem uses stdin and stdout to move data around, making it pretty trivial for a programmer to simply use minimodem as a data transfer frontend and simply implement any decoding or compression necessary in the program getting and putting data via pipes, see my easrelay program for example. Just my $0.02.

**Comment by kamalmostafa** [comment]
Good answer, @nkeck720.  Note that minimodem can certainly --tx and --rx at any baud rate up to half the bandwidth of the audio channel, but only encodes and decodes simple FSK-based protocols.
